name: Hellow World

on:
    push:
        branches:
            - 0_course_start

jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "Hello World!"
